version: 2
registries:
  commons-github-actions:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.ACCESS_TO_GITHUB}}

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    registries:
      - commons-github-actions
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[COMMONS-GITHUB-ACTIONS]"
    allow:
      - dependency-name: premisedata/commons-github-actions
