

version: 2
registries:
  commons-github-actions:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GITHUB_TOKEN}}

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    registries:
      - commons-github-actions
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "[COMMON-GITHUB-ACTIONS]"
    labels:
      - "Goblet"
    allow:
      - dependency-name: premisedata/commons-github-actions
