version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[DP_DEPLOY_GOBLET]"
    open-pull-requests-limit: 2
    allow:
      - dependency-name: premisedata/commons-github-actions/.github/workflows/dp_deploy_goblet.yml*