name: Update api names list
on:
  workflow_dispatch:

jobs:
  Update:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: "projects/102075874751/locations/global/workloadIdentityPools/gh-places-deploy-dev/providers/gh-places-dev-provider"
        service_account: "deploy-cloudrun-cicd@premise-places-dev.iam.gserviceaccount.com"
        token_format: access_token
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Install gcloud beta
      run: gcloud components install beta
    - name: Listing auths
      run:  gcloud auth list --filter=status:ACTIVE --format="value(account)"
    - name: Python setup
      uses: actions/setup-python@v4
    - name: Install google api
      run: pip install google-api-python-client
#    - name: Runing python list
#      run: >
#        python test_api_list.py
    - name: List services
      run: > 
          gcloud beta services list
