name: Update api names list
on:
  workflow_dispatch:
  schedule:
    - cron: '00 * * * *'
jobs:
  Update:
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { ref: main }
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: "projects/963616447866/locations/global/workloadIdentityPools/gh-deploy-dev-portal-rd/providers/gh-dev-portal-provider-rd"
        service_account: "gha-enable-apis@premise-developer-portal-rd.iam.gserviceaccount.com"
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Install gcloud beta
      run: gcloud components install beta

    - name: Config gcloud
      run: gcloud config set account gha-enable-apis@premise-developer-portal-rd.iam.gserviceaccount:com

    - name: Generate temporal api list file
      run: > 
          gcloud beta services list --available --format='value(NAME)' --filter="NAME:googleapis" > ./packages/backend/public/apis.tmp

    - name: Create branch update-api-name-list
      run: >
          git checkout -B update-api-name-list origin/main

    - name: Config git email
      run: >
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Config git user name
      run: >
          git config --local user.name "github-actions[bot]"

    - name: Remove old file
      run: >
          git rm ./packages/backend/public/apis.txt

    - name: Create updated api.txt file
      run: >
          cat ./packages/backend/public/apis.tmp > ./packages/backend/public/apis.txt

    - name: Add updated api.txt file and commit
      run: >
          git add ./packages/backend/public/apis.txt

    - name: Commit allowing empty changes
      run: >
          git commit --allow-empty -m "[UPDATE] api names list for developer portal"

    - name: Set upstream git branch name to update-api-name-list
      run: >
        git push --set-upstream origin update-api-name-list --force

    - name: Push to update-api-name-list
      run: >
        git push
    - name: create pull request
      run: >
        gh pr create -B main -H update-api-name-list --title '[Created by Github action] Update api names list' --body 'Update api names list for developer portal Enable GCP Service API template'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
