name: Update api names list
on:
  workflow_dispatch:

jobs:
  Update:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: "projects/963616447866/locations/global/workloadIdentityPools/gh-deploy-dev-portal-rd/providers/gh-dev-portal-provider-rd"
        service_account: "sa-developer-portal-rd@premise-developer-portal-rd.iam.gserviceaccount.com"

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Install gcloud beta
      run: gcloud components install beta
    - name: Listing auths
      run:  gcloud auth list --filter=status:ACTIVE --format="value(account)"
    - name: Python setup
      uses: actions/setup-python@v4
    - name: Install google api
      run: pip install google-api-python-client

    - name: List services
      run: > 
          gcloud beta services list
