name: Update api names list
on:
  workflow_dispatch:

jobs:
  Update:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.8.3'
      with:
        workload_identity_provider: "projects/963616447866/locations/global/workloadIdentityPools/gh-deploy-dev-portal-rd/providers/gh-dev-portal-provider-rd"
        service_account: "sa-developer-portal-rd@premise-developer-portal-rd.iam.gserviceaccount.com"
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: '355.0.0'
    - name: Install gcloud beta
      run: gcloud components install beta
    - name: List services
      run: gcloud services list --available --filter="name:*.googleapis.com" --project=premise-developer-portal-rd
      