name: Semver

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Minor/Patch release
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0
    - name: Increment version
      id: increment_version
      uses: paulhatch/semantic-version@v5.3.0
      with:
        tag_prefix: ""
        major_pattern: (MAJOR)
        minor_pattern: (MINOR)
        version_format: ${major}.${minor}.${patch}
        debug: true
    - name: Tag
      if: ${{ steps.increment_version.outputs.version_type == 'minor' || steps.increment_version.outputs.version_type == 'patch' }}
      run: |
        git tag ${{ steps.increment_version.outputs.version }}
        git push origin ${{ steps.increment_version.outputs.version }}
    - name: Release
      if: ${{ steps.increment_version.outputs.version_type == 'minor' || steps.increment_version.outputs.version_type == 'patch' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.increment_version.outputs.version }}
        release_name: Release ${{ steps.increment_version.outputs.version }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        
        
        
