name: "Test"

on:
  workflow_dispatch:


permissions:
  contents: "write"
  id-token: "write"
  pull-requests: write

jobs:
    Deploy:
      uses: premisedata/commons-github-actions/.github/workflows/dp_deploy_goblet.yml@1.1.1
